BAG=/home/garage2/pccts/bin/bag
SRC=test.c rexpr.c
OBJ=test.o rexpr.o
CFLAGS = -g

test: $(OBJ) $(SRC)
	cc -g -o test $(OBJ)

shar:
	shar makefile test.c rexpr.c > rexpr.shar

archive:
	$(BAG) makefile test.c rexpr.c > rexpr.bag
